### ISSUE TITLE
HTTP 415 - Unsupported Media Type

### ISSUE THREAD

**Issue by adamstauffer** [gbezyuk/django-crowd#9]
Using Crowd version 2.11.1 here, we seem to get back `HTTP Status 415 - Unsupported Media Type` when attempting to authenticate using the options specified in https://github.com/gbezyuk/django-crowd/blob/master/crowd/backends.py#L61 

Specifically, when we change the content-type header to `application/xml` it seems to work. I don't know if this used to work in older versions of Crowd the [Crowd API Documentation](https://docs.atlassian.com/atlassian-crowd/latest/REST/#usermanagement/1/authentication) doesn't seem to provide any examples where the content-type is set.

**Comment by gbezyuk** [comment]
Fixed with #10 (actually I didn't test, but if you say so)
